# Site settings
title: Andreas Pick
email: andreas.pick@cantab.net
office: Department of Econometrics
address: PO Box 1738, NL-3000 DR Rotterdam
#telephone:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://people.few.eur.nl/pick/" # the base hostname & protocol for your site
#twitter_username: "@apickeu"
#github_username:  "ap236"

# Build settings
markdown: kramdown

# added by ap:
defaults:
  -
    scope:
      path: "" # empty string means applies to all files
      # type: "posts"
    values:
      layout: "default" # shouldn't change anything
  -
    scope:
      path: "" # empty string means applies to all files
      # type: "pages"
    values:
      layout: "default" # shouldn't change anythine.g. g
